#!/usr/bin/env python3
"""
Medical Report AI — Interactive launcher.
Run this script to:
  1. Prompt for the Supabase DB password (if not already set).
  2. Write .env with the correct DATABASE_URL.
  3. Install Python dependencies.
  4. Initialize the Supabase database schema.
  5. Start the Flask server.

Usage:
  python run.py
"""
import os
import sys
import subprocess
import getpass
import shutil

ROOT = os.path.dirname(os.path.abspath(__file__))
BACKEND_DIR = os.path.join(ROOT, "backend")
ENV_EXAMPLE = os.path.join(ROOT, ".env.example")
ENV_FILE = os.path.join(ROOT, ".env")
REQUIREMENTS = os.path.join(ROOT, "requirements.txt")

SUPABASE_URL = "https://byorfonxmgmitvwflofx.supabase.co"
SUPABASE_KEY = "sb_publishable_Zw3Gp1Vojw2GQfWKmUz2Jg_ruFJUoCw"
PROJECT_REF = "byorfonxmgmitvwflofx"
BOB_API_KEY = "azI6ZGM4ODQzYWEtOTdhOC00Njg4LWIxZjAtNDc5ZWFiZjZmNzQ3OlU5czdHVEVFK0VOVGQ5N0NMajZoK3N3dFR4UGJlTmR6dWNrdzQvL3k5d2M9"
BOB_API_BASE_URL = "https://api.us-east.bob.ibm.com/inference/v1"
BOB_MODEL = "granite3.3:8b"

BANNER = """
╔══════════════════════════════════════════════════════╗
║         Medical Report AI — Launcher                ║
╚══════════════════════════════════════════════════════╝
"""


def banner():
    print(BANNER)


def step(n, msg):
    print(f"\n[{n}] {msg}")
    print("─" * 54)


def ok(msg):
    print(f"    ✓ {msg}")


def warn(msg):
    print(f"    ⚠ {msg}")


def err(msg):
    print(f"    ✗ {msg}")


# ──────────────────────────────────────────────────────────────
# Step 1: Resolve DB password + write .env
# ──────────────────────────────────────────────────────────────
def get_db_password() -> str:
    """Read DB password from .env if already set, otherwise prompt."""
    # Check if .env already has a real password
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                if line.startswith("DATABASE_URL=") and "YOUR_DB_PASSWORD" not in line:
                    url = line.strip().split("=", 1)[1]
                    # Extract password from URL
                    try:
                        from urllib.parse import urlparse
                        parsed = urlparse(url)
                        if parsed.password and len(parsed.password) > 4:
                            ok(f".env already has DATABASE_URL set.")
                            return parsed.password
                    except Exception:
                        pass

    print("""
    Supabase direct PostgreSQL password needed.
    Find it at: Supabase Dashboard → Project Settings → Database → Database password
    """)
    while True:
        pwd = getpass.getpass("    Enter your Supabase DB password: ").strip()
        if pwd:
            return pwd
        print("    Password cannot be empty. Try again.")


def write_env(db_password: str):
    """Write .env file with all settings."""
    region = "us-east-1"  # default; Supabase may vary
    db_url = (
        f"postgresql://postgres.{PROJECT_REF}:{db_password}"
        f"@aws-0-{region}.pooler.supabase.com:6543/postgres"
    )
    content = f"""# Medical Report AI — generated by run.py
FLASK_ENV=development
FLASK_SECRET_KEY=med-report-ai-{PROJECT_REF[:8]}-secret
FLASK_PORT=5000

SUPABASE_URL={SUPABASE_URL}
SUPABASE_KEY={SUPABASE_KEY}

DATABASE_URL={db_url}

BOB_API_BASE_URL={BOB_API_BASE_URL}
BOB_API_KEY={BOB_API_KEY}
BOB_MODEL={BOB_MODEL}

UPLOAD_FOLDER=uploads
MAX_CONTENT_LENGTH_MB=50

OTP_DEV_MODE=true
OTP_EXPIRY_MINUTES=10
"""
    with open(ENV_FILE, "w") as f:
        f.write(content)
    ok(f".env written with DATABASE_URL for Supabase project {PROJECT_REF}")
    return db_url


# ──────────────────────────────────────────────────────────────
# Step 2: Install dependencies
# ──────────────────────────────────────────────────────────────
def install_deps():
    step(2, "Installing Python dependencies")
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", "-r", REQUIREMENTS, "-q"],
            capture_output=True, text=True, timeout=180
        )
        if result.returncode == 0:
            ok("All dependencies installed.")
        else:
            warn("Some packages may have failed. Check output:")
            print(result.stdout[-1000:] if result.stdout else "")
            print(result.stderr[-500:] if result.stderr else "")
    except subprocess.TimeoutExpired:
        warn("pip install timed out — check your internet connection.")
    except Exception as e:
        warn(f"pip install error: {e}")


# ──────────────────────────────────────────────────────────────
# Step 3: Test DB connection + initialize schema
# ──────────────────────────────────────────────────────────────
def init_database(db_url: str):
    step(3, "Connecting to Supabase PostgreSQL and initializing schema")
    sys.path.insert(0, BACKEND_DIR)
    # Reload config with new .env
    import importlib
    if "config" in sys.modules:
        importlib.reload(sys.modules["config"])
    if "database" in sys.modules:
        importlib.reload(sys.modules["database"])

    try:
        from database import init_db, get_connection
        # Test connection first
        conn = get_connection()
        conn.close()
        ok("Database connection successful.")
        # Initialize schema
        init_db()
        ok("Schema initialized (tables created if not exist).")
    except Exception as e:
        err(f"Database error: {e}")
        print("""
    Troubleshooting:
    • Check your DB password is correct
    • Try the session pooler URL from Supabase:
      Dashboard → Project Settings → Database → Connection string → Session mode
    • The URL format should be:
      postgresql://postgres.{project_ref}:{password}@aws-0-{region}.pooler.supabase.com:6543/postgres
        """)
        sys.exit(1)


# ──────────────────────────────────────────────────────────────
# Step 4: Test BOB API
# ──────────────────────────────────────────────────────────────
def test_bob_api():
    step(4, f"Testing BOB API ({BOB_API_BASE_URL})")
    try:
        import requests as req
        import base64
        raw_key = base64.b64decode(BOB_API_KEY).decode("utf-8")
        r = req.post(
            f"{BOB_API_BASE_URL}/chat/completions",
            json={"model": BOB_MODEL, "messages": [{"role": "user", "content": "Say: OK"}], "max_tokens": 5},
            headers={"Authorization": f"Bearer {raw_key}", "Content-Type": "application/json", "User-Agent": "medical-report-ai/1.0"},
            timeout=15,
        )
        if r.status_code == 200:
            ok(f"BOB API reachable. Model: {BOB_MODEL}")
        else:
            warn(f"BOB API returned HTTP {r.status_code}: {r.text[:200]}")
            warn("AI features will show errors until the API key is valid.")
    except Exception as e:
        warn(f"BOB API not reachable: {e}")
        warn("AI features will show errors. The app will still run.")


# ──────────────────────────────────────────────────────────────
# Step 5: Start Flask
# ──────────────────────────────────────────────────────────────
def start_server():
    step(5, "Starting Flask server")
    port = 5000
    print(f"\n    ┌────────────────────────────────────────┐")
    print(f"    │  Medical Report AI                     │")
    print(f"    │  http://localhost:{port}                  │")
    print(f"    │  Press Ctrl+C to stop                  │")
    print(f"    └────────────────────────────────────────┘\n")
    os.chdir(BACKEND_DIR)
    os.execv(sys.executable, [sys.executable, "app.py"])


# ──────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────
if __name__ == "__main__":
    banner()

    step(1, "Setting up environment")
    db_password = get_db_password()
    db_url = write_env(db_password)

    install_deps()
    init_database(db_url)
    test_bob_api()
    start_server()
